const PLACE_ID = 2753915549;
const POLL_MS = Math.max(30000, Number(process.env.FM_POLL_MS) || 60000);
const FM_SOURCE_URL = process.env.FM_SOURCE_URL || 'https://hostserver.porry.store/bloxfruit/bot/JobId/fullmoon';
const SOURCE_TIMEOUT_MS = Math.max(3000, Number(process.env.FM_SOURCE_TIMEOUT_MS) || 10000);
const MAX_SERVER_PAGES = Math.max(1, Math.min(3, Number(process.env.FM_SERVER_PAGES) || 2));
const RETRY_AFTER_429_MS = 65000;
const state = {running:false,lastScanAt:null,lastSourceAt:null,lastSourceStatus:null,servers:new Map(),fullMoonReports:new Map(),lastError:null,nextAllowedScanAt:0};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fetchServers(cursor=null){const url=new URL(`https://games.roblox.com/v1/games/${PLACE_ID}/servers/Public`);url.searchParams.set('sortOrder','2');url.searchParams.set('excludeFullGames','true');url.searchParams.set('limit','100');if(cursor)url.searchParams.set('cursor',cursor);const response=await fetch(url,{headers:{'User-Agent':'BloxServer-FM-Finder/1.0','Accept':'application/json'}});if(response.status===429){state.nextAllowedScanAt=Date.now()+RETRY_AFTER_429_MS;throw new Error('Roblox servers API rate limited (429); backing off for 65 seconds.');}if(!response.ok)throw new Error(`Roblox servers API returned ${response.status}`);return response.json();}
function collectJobIds(value,result=new Set()){if(typeof value==='string'){const m=value.match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/gi);if(m)m.forEach(id=>result.add(id));return result;}if(Array.isArray(value)){for(const x of value)collectJobIds(x,result);return result;}if(value&&typeof value==='object')for(const x of Object.values(value))collectJobIds(x,result);return result;}
async function fetchFullMoonSource(){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),SOURCE_TIMEOUT_MS);try{const response=await fetch(FM_SOURCE_URL,{headers:{Accept:'application/json,text/plain,*/*'},signal:controller.signal});state.lastSourceStatus=response.status;if(!response.ok)throw new Error(`FM source returned HTTP ${response.status}`);const text=await response.text();state.lastSourceAt=new Date().toISOString();let parsed=text;try{parsed=JSON.parse(text)}catch(_){}return [...collectJobIds(parsed)];}finally{clearTimeout(timer);}}
function pruneReports(){const cutoff=Date.now()-120000;for(const [id,r] of state.fullMoonReports)if(r.reportedAt<cutoff)state.fullMoonReports.delete(id);}
async function scanOnce(force=false){if(state.running)return;if(!force&&Date.now()<state.nextAllowedScanAt)return;state.running=true;state.lastError=null;try{let cursor=null;for(let p=0;p<MAX_SERVER_PAGES;p++){const page=await fetchServers(cursor);for(const s of page.data||[])state.servers.set(s.id,{jobId:s.id,playing:s.playing,maxPlayers:s.maxPlayers,seenAt:Date.now()});cursor=page.nextPageCursor||null;if(!cursor)break;await sleep(2000);}const jobIds=await fetchFullMoonSource();const now=Date.now();const live=new Set(jobIds);for(const [id,r] of state.fullMoonReports)if(!live.has(id)||now-r.reportedAt>=120000)state.fullMoonReports.delete(id);for(const id of jobIds){const known=state.servers.get(id);if(!known)continue;state.fullMoonReports.set(id,{jobId:id,fullMoon:true,playing:known.playing,maxPlayers:known.maxPlayers,reportedAt:now,source:FM_SOURCE_URL});}pruneReports();state.lastScanAt=new Date().toISOString();}catch(e){state.lastError=e.message;state.lastScanAt=new Date().toISOString();}finally{state.running=false;}}
scanOnce();setInterval(scanOnce,POLL_MS);module.exports={state,scanOnce,PLACE_ID,FM_SOURCE_URL};