const http = require('http');
const crypto = require('crypto');
const { Client, GatewayIntentBits, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const PREFIX='.'; const PLACE_ID=2753915549; const PORT=Number(process.env.PORT)||10000;
const token=process.env.DISCORD_BOT_TOKEN; const REPORT_SECRET=process.env.FM_REPORT_SECRET||'';
const REPORT_MAX_AGE_MS=2*60*1000;
const OBSERVER_URL=process.env.FRUIT_SOURCE_URL||'https://www.fruitnotifier.live/';
const OBSERVER_POLL_MS=Math.max(30000,Number(process.env.FRUIT_POLL_MS)||60000);
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const fruitReports=new Map(); let observerRunning=false; let observerLastAt=null; let observerError=null;
if(!token){console.error('Missing DISCORD_BOT_TOKEN environment variable.');process.exit(1);}
function timingSafeEqual(a,b){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)}
function joinUrl(jobId){return `https://www.roblox.com/games/start?placeId=${PLACE_ID}&gameInstanceId=${encodeURIComponent(jobId)}`}
function normalizeFruitName(v){return String(v||'').replace(/\s+/g,' ').trim().slice(0,80)}
function freshReports(){const cutoff=Date.now()-REPORT_MAX_AGE_MS;for(const[id,r]of fruitReports)if(r.reportedAt<cutoff)fruitReports.delete(id);return [...fruitReports.values()].sort((a,b)=>b.reportedAt-a.reportedAt)}
function addReport(r){if(!r.jobId||!r.fruit)return false;fruitReports.set(`${r.jobId}:${r.fruit.toLowerCase()}`,r);return true}
function buildFruitMessage(reports){const lines=['🍎 **Blox Fruits — Live Fruit Servers**','',''];const rows=[];reports.slice(0,25).forEach((r,i)=>{const status=r.present?'🟢 **PRESENT**':'🔴 **TAKEN**';lines.push(`**${i+1}. ${normalizeFruitName(r.fruit)}** — ${status}`,`👥 ${r.playing??'?'} / ${r.maxPlayers??'?'}`);const ri=Math.floor(i/5);if(!rows[ri])rows[ri]=new ActionRowBuilder();rows[ri].addComponents(new ButtonBuilder().setLabel(`Join #${i+1}`).setStyle(ButtonStyle.Link).setURL(joinUrl(r.jobId)));});lines.push('','🔄 Live observer data.');return{content:lines.join('\n'),components:rows}}
async function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>20000){req.destroy();reject(new Error('body too large'))}});req.on('end',()=>resolve(b));req.on('error',reject)})}
async function pollObserver(){if(observerRunning)return;observerRunning=true;observerError=null;try{const controller=new AbortController();const t=setTimeout(()=>controller.abort(),15000);const r=await fetch(OBSERVER_URL,{headers:{'User-Agent':'Blox-server-fruit-observer/1.0','Accept':'text/html,application/json'},signal:controller.signal});clearTimeout(t);if(!r.ok)throw new Error(`observer HTTP ${r.status}`);const text=await r.text();observerLastAt=new Date().toISOString();
  // Prefer full Roblox join links if the observer exposes them. We extract the server JobId from gameInstanceId.
  const hrefRe=/https?:\/\/www\.roblox\.com\/games\/start\?[^"'<>\s]*gameInstanceId=([^&"'<>\s]+)/gi; const links=[]; let m; while((m=hrefRe.exec(text))!==null){const id=decodeURIComponent(m[1]);if(/^[0-9a-f-]{20,64}$/i.test(id)&&!links.includes(id))links.push(id)}
  // Also support JSON observers that return jobId/fruit fields.
  try{const j=JSON.parse(text);const walk=(x)=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}if(x.jobId&&x.fruit){addReport({jobId:String(x.jobId),fruit:normalizeFruitName(x.fruit),present:x.present!==false,playing:Number.isFinite(Number(x.playing))?Number(x.playing):null,maxPlayers:Number.isFinite(Number(x.maxPlayers))?Number(x.maxPlayers):12,reportedAt:Date.now(),source:OBSERVER_URL})}Object.values(x).forEach(walk)};walk(j)}catch(_){ }
  // If the HTML contains server cards, associate each join link with the nearest fruit name and player count.
  const fruitNames=['Dragon (East)','Dragon (West)','Tiger','Kitsune','T-Rex','Buddha','Portal','Pain','Lightning','Spirit','Gas','Yeti','Mammoth','Dough','Shadow','Venom','Control','Trex','Phoenix','Blizzard','Gravity','Sound','Spirit','Love','Spider','Creation','Quake','Magma','Ghost','Light','Dark','Diamond','Rubber','Barrier','Blossom','Flame','Ice','Sand','Falcon','Smoke','Bomb','Spike','Spring','Chop','Rocket','Spin'];
  links.forEach((jobId,i)=>{const pos=text.indexOf(jobId);const chunk=text.slice(Math.max(0,pos-2500),Math.min(text.length,pos+800));const fruit=fruitNames.find(n=>new RegExp(n.replace(/[()]/g,'\\$&'),'i').test(chunk));const pm=chunk.match(/(\d{1,2})\s*\/\s*12/);if(fruit)addReport({jobId,fruit,present:true,playing:pm?Number(pm[1]):null,maxPlayers:12,reportedAt:Date.now(),source:OBSERVER_URL})});
  freshReports();
 }catch(e){observerError=e.name==='AbortError'?'observer timeout':e.message}finally{observerRunning=false}}
setInterval(pollObserver,OBSERVER_POLL_MS); pollObserver();
const server=http.createServer(async(req,res)=>{if(req.url==='/'||req.url==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({status:'ok',bot:client.isReady()?'online':'starting',prefix:PREFIX,fruitReports:freshReports().length,observer:OBSERVER_URL,observerLastAt,observerError}))}if(req.method==='GET'&&req.url==='/fruits'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify(freshReports().map((r,i)=>({...r,rank:i+1,joinUrl:joinUrl(r.jobId)}))))}if(req.method==='POST'&&req.url==='/observer/fruits'){try{const provided=req.headers['x-fm-secret'];if(!REPORT_SECRET||typeof provided!=='string'||!timingSafeEqual(provided,REPORT_SECRET)){res.writeHead(401,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'unauthorized'}))}const body=JSON.parse(await readBody(req));const jobId=String(body.jobId||'').trim(),fruit=normalizeFruitName(body.fruit),reportedAt=Number(body.reportedAt||Date.now());if(!/^[0-9a-f-]{20,64}$/i.test(jobId)||!fruit||!Number.isFinite(reportedAt)||Math.abs(Date.now()-reportedAt)>REPORT_MAX_AGE_MS){res.writeHead(400,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'invalid or stale report'}))}addReport({jobId,fruit,present:body.present===true||String(body.status||'').toLowerCase()==='present',playing:Number.isFinite(Number(body.playing))?Number(body.playing):null,maxPlayers:Number.isFinite(Number(body.maxPlayers))?Number(body.maxPlayers):12,reportedAt,source:'observer'});res.writeHead(202,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true,jobId,fruit,joinUrl:joinUrl(jobId)}))}catch(e){res.writeHead(400,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'invalid request'}))}}res.writeHead(404,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Not found'}))});
server.listen(PORT,'0.0.0.0',()=>console.log(`Health server listening on port ${PORT}`));
client.once('ready',()=>console.log(`${client.user.tag} is online! Default prefix: ${PREFIX}`));
client.on('messageCreate',async message=>{if(message.author.bot||!message.content.startsWith(PREFIX))return;const parts=message.content.slice(PREFIX.length).trim().split(/\s+/);const command=(parts.shift()||'').toLowerCase();if(command==='ping'){await message.reply('pong');return}if(command==='find'&&parts.shift()?.toLowerCase()==='fruits'){const reports=freshReports();if(!reports.length){await message.reply('🍎 **No live fruit servers are available yet.** The observer is updating automatically. Try again in a few seconds.');return}await message.reply(buildFruitMessage(reports))}});
client.login(token).catch(e=>{console.error('Discord login failed:',e);process.exit(1)});
